### ISSUE TITLE
[CRASH]: Geophilic exception generating new chunk, found "diamond_ore_medium"

### ISSUE THREAD

**Issue by vinnyg0621** [everloste/my-mc-projects#10] opened 2024-09-25 06:49 UTC
**Mod and game version**
Minecraft forge 1.20.1 - 47.3.10, mod latest version (3.1.3)

**Describe the bug**

### EXIT CODE: -1
game crashes when generating a new chunk in world because apparently "minecraft:worldgen/placed_feature/minecraft:ore_diamond_medium" is missing.
this is because "ore_diamond_medium" is not in the files anymore since 3.0

**To reproduce (optional)**
1. Join a world or create a new one
2. click on "create new world" or "join world" on _any_ world!
3. wait for the game to crash and world to break

**Additional context (optional)**
I suggest adding back that placed feature back to the files to stop causing that crash

Thank you!

**Comment by everloste** [comment] 2024-09-25 08:41
duplicate of #3 which was closed with a thorough explanation. please do not recreate this issue again.

**Closed as not planned** 2024-09-25 08:41 UTC
Labels: #bug, #duplicate
